### ISSUE TITLE
Thanks for your package! 👍

### ISSUE THREAD

**Issue by simonrenoult** [edvinh/node-sloc#11]
Hi there 👋

As a fellow package maintainer, I wanted to thank you for your work :pray: 
I noticed you pushed an update to support TypeScript, that's awesome!
Just so you know, I'm actually using your package in a package I'm maintaining: https://github.com/simonrenoult/code-complexity 

Have a good day,
Simon

**Comment by edvinh** [comment]
Hey Simon, I'm glad you like the package! I see that it's coming to good use. I've actually taken a look at `code-complexity` before -- it's a pretty cool tool :)
