### ISSUE TITLE
i'd like to count SPEC file SLOC

### ISSUE THREAD

**Issue by michahell** [edvinh/node-sloc#12]
By doing something like this:
```npx node-sloc -v -d -e "spec.js" --ignore-paths "node_modules" ./```

But i'm getting the following error:
`Error when walking directory: TypeError: Reduce of empty array with no initial value`

Probably due to spec.js not being an extension.
how can I count only `spec.ts` files?

**Comment by edvinh** [comment]
Hi Michael, thanks for opening this issue.

Unfortunately this is a case that `node-sloc` doesn't support. It might be a good idea to add it, but I've been thinking about a different approach to address these types of limitations -- namely adding glob support for the path argument as well. However I'm not too sure what it should look like yet. A possibility would be to include a --glob flag, but I'd have to figure out how to combine that with existing flags.

**Comment by michahell** [comment]
Understood, I was assuming as much! I've managed to figure out what I needed with another SLOC tool 👍
