### ISSUE TITLE
fetch takes about 10 seconds

### ISSUE THREAD

**Issue by gvasquez95** [edvinh/node-sloc#3]
Tried both from my local dev environment and from an AWS Lambda, to rule out the connection speed issue, but on both scenarios retrieving approx 200 repositories takes about 10 seconds and, I'm wondering if HTTP connection reuse is in place.

I'm using the CLI version

**Comment by edvinh** [comment]
@gvasquez95 I'm assuming you wanted to open this issue on another repo? `node-sloc` doesn't contain anything related to HTTP connections.
